[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5
via_ir = true
optimizer = true
optimizer_runs = 200
auto_detect_solc = true

# Set EVM version to london to avoid PUSH0 issues
evm_version = "london"


[etherscan]
celo = { key = "placeholder", url = "https://explorer.celo.org/mainnet/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config