[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5
via_ir = true
optimizer = true
optimizer_runs = 200


[etherscan]
celo = { key = "placeholder", url = "https://explorer.celo.org/mainnet/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config